# Generated by Django 5.0.2 on 2025-10-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tiendify_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materias',
        ),
    ]
