# Generated by Django 5.0.2 on 2025-10-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tiendify_api', '0002_delete_materias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajadores',
            old_name='clave_alumno',
            new_name='clave_trabajador',
        ),
    ]
