# Generated by Django 5.0.2 on 2025-10-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tiendify_api', '0003_rename_clave_alumno_trabajadores_clave_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadores',
            name='curp',
        ),
    ]
