# Generated by Django 5.0.2 on 2025-10-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tiendify_api', '0004_remove_trabajadores_curp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadores',
            name='fecha_de_Nacimiento',
        ),
    ]
