# Generated by Django 5.0.2 on 2025-11-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tiendify_api', '0009_alter_venta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
