# Generated by Django 5.0.2 on 2025-11-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tiendify_api', '0010_alter_ventadetalle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
