# Generated by Django 5.0.2 on 2025-11-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tiendify_api', '0011_producto_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
