# Generated by Django 5.0.2 on 2025-11-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_tiendify_api', '0012_producto_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(max_length=40)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
